mayannah/config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
from rest_framework_jwt.views import obtain_jwt_token, verify_jwt_token, refresh_jwt_token

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^remittance/', include('partner.urls', namespace='partner')),
    # Rest Framework Browsable API
    url(r'^api-auth/', include('rest_framework.urls',
                       namespace='rest_framework')),
    url(r'^v1/', include('v1.urls', namespace='v1')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^profile/', include('person.urls', namespace='profile')),
    url(r'^health/', include('health.urls', namespace='health')),
    url('^$', RedirectView.as_view(pattern_name='profile:self'), name='home'),
    # JWT
    url(r'^api-token-auth/', obtain_jwt_token),
    url(r'^api-token-verify/', verify_jwt_token),
    url(r'^api-token-refresh/', refresh_jwt_token),
]

mayannah/partner/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='list'),
    url(r'^(?P<slug>[-\w]+)/$',
        views.RemittanceDetailView.as_view(), name='detail')
]

mayannah/v1/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from v1.views import RemittanceList, RemittanceDetail, RemittancePay, \
                     TransactionDetail, TransactionCreate, TransactionPay

urlpatterns = [
        url(r'^remittance/$', RemittanceList.as_view()),
        url(r'^remittance/search/$', RemittanceDetail.as_view()),
        url(r'^remittance/pay/$',
                    RemittancePay.as_view()),
        # Transactions
        url(r'^transaction/$', TransactionCreate.as_view()),
        url(r'^transaction/complete/$', TransactionPay.as_view()),
        url(r'^transaction/(?P<reference_id>[-\w]+)/$', TransactionDetail.as_view()),

        ]

urlpatterns = format_suffix_patterns(urlpatterns)

mayannah/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <!-- Compiled and minified CSS -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css">

        <!-- Compiled and minified JavaScript -->
          <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>
</head>
<body>
    <header>
        <div class="container">
            <ul>
                <li>
                    <a href="{% url 'profile:self' %}">Profile</a>
                </li>
                <li>
                    <a href="{% url 'partner:list' %}">Remittance</a>
                </li>
                {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'account_logout' %}">Logout</a>
                </li>
                    {% if not user.has_usable_password %}
                    <li>
                        <a href="{% url 'account_set_password' %}">SET PASSWORD!!!</a>
                    </li>
                    {% endif %}
                {% else %}
                <li>
                    <a href="{% url 'account_login' %}">Login</a>
                <li>
                {% endif %}
            </ul>
        </div>

    </header>
{% block body %}
<div class="container">

{% block content %}
{% endblock content %}
</div>
{% endblock body %}
{% block extra_body %}
{% endblock extra_body%}
</body>
</html>

mayannah/templates/layout.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link href="https://fonts.googleapis.com/css?family=Montserrat"
    rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">
    <title>Mayannah</title>
</head>
<body>
    <header>
        <div class="container"><a href="{% url 'partner:list' %}">Remittance</a></div>
    </header>
    <div class="main_body">
        {% block body %}
        {% endblock %}
    </div>

    <!--Import jQuery before materialize.js-->
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>
</body>
</html>